language: ruby
rvm:
  - 2.2
script: bundle exec jekyll build
deploy:
  provider: s3
  access_key_id:
    secure: "M1coLYV4ABT3tZ9S4QszwIfNyhZ3hQafo6z2j/qG0SyXJ9s7tARfxhoC05l45Zpr09abhZwxdSHkp/QOatnX75Ci5/2mMvCgpcGiDVCVNOvOKU5BB57GHQ6AKgcutHAC5+2PsHGJbOiKxgWZnZ080CKE6027VdFR+PVF87IH3f1rFYlclR3epASGESV0tbmiWOEoE2qDFlVcmauEuIwnigxU18E/5oFHfZfwfo527eLpU3bEt0jPQS4sIihH1tX6c66Wa5U7K0oLgqQh/flbgCadZnm+tQk/80QeJ7AiEMChfol7qwxg12Gj0B25h88xbDamlEpqu2l2fN0beYjLqVYN7N97RG/uaBcoAOB1/+HtGTMcRlWtwFL2t98cyGi6c9xCtNksu/ENjgT76okdJ5yOzvKkrT7rxelQl4y9VVCC6kR97CEMGsGhcD4Yv8Xn5+H5HY5zGtHDbUDi43GR6U+GjjcVHe1L6BPlf7Z9DEwD9CYCDoJBxAWLBLSglOARAj6oyRSD8ywD+zLmrBn0fHB9rCMBUCkzl+bM7zCAlC1Ja6UkFcPm6kzEk3lKxUFbAjYYBuLVfb0L2of/aKZHvMULhsLZLcg65NaMGJcfrzDqmj5eh0yiq1MONSHVhsILzAvgvbbB0OR/XHQC4evdGGgCAaVGhSTm6ijw8HWTfbQ="
  secret_access_key:
    secure: "yfCw3n3ZFHx5ObmUrWJmfnNuO4lV51NXV7VbXUXO+ppxF/9jvSQsIw4PHGJVDSSrJppYpycA4N8c6Dj8iPIL1VmMW9eucyIMHKsNLmq9JnHjEQSK1QGvUtR0rlHW3qLy/HBql3Y7adsydoFm+4Gde7CiRP1aJnCSiiWP0jJbnOLCAE4k51epOr1SbHQ4yo9i/1JbhQ0iasvdQ+WEphJBDf3hAyxh1FUNmqwDRpgdYeYItIyQATFRAlJRoKMARPXKEB1/p4+bPIeWOHzIgj6u5j2Pzw9sQDf4IGynX72ibUq/VNFEg5jw4YUO6NA8Ouq+oB9Kke2qBOgB76SmgQBOzfnvY04Ol9HQddOPKysVYcQzH2DpSAU9DV49XYR4EyR/xBo2iMLWLr9Yk3ExOVxFR1d7pkA+wlhg5L9U9+jhZyWyaYSmgs4qfbFc+gkndQPrJ8sewQS8rcPv0iLl+53D7eA2oDb9N0/2GciYIDH/olKi5YLZZTQmLmnTiozbbR1fWke5B8vezI8M47ZNlJti4Ng1GVV3Yy751qwvEWxfvBT2UxESplNAkMyyjPLKaozH5SDHdFywgKysHLX0DiIXHd5tziO00Dpb9JamSg4xH3WI6bwwsxqjbKVPMgjyeiRn21Bdb1ON51KkbZiT+/3WXveK5aKlILoP8DPGaYdZFyc="
  bucket: cagataygurturk.com
  skip_cleanup: true
  region: eu-west-1
  local_dir: _site