language: ruby
rvm:
  - 2.2
script: bundle exec jekyll build
deploy:
  provider: s3
  access_key_id:
    secure: "pedcz1YpKywFax78tSgNASOENVFNtaVtVvbY7a/4EbzIOXdWSGc4vWbpAm1yeE9WQJ+fX41iVSrhWutZlWMtfqfI0m4i/wJzRzfWDKG5VYrZQvLVUCmWmIG3iC2P5cmdtaG24CuEHUVPJX2k6wS1PbZgd6JKc3tQYXTo29cbo+U1qs1bfTNRC4t5xJ1UzsttDA0h/mxVAiJWV7nQIAFY4Bd5q/dZrCzignddYUFV8WpnJWs6QfhxXUA0PotRaZQIYg/0Bkk2eu71IZk4rAC53+fiAx28Q5Yib2VAt/xUzz8tBBmV83fntprE4nwdmW4XyM4kBR54HSw2+akHxpu4Xlh20zRISNkW/Z3OelZicbTd8L/Jpf4qgwejigGPRIWNSBUefprR7RYz6XiGNIadSiluANR21vgZYdf+aclCmH9EbIL17KZJjCzSgtIT1AE5Arw7jnvcJG7cMiEErl401v3hqf6WVbN8k4fI154X7BgiarqOrR8A8QU0b4QSw5oz6qjr97rPXDiKxHTJML8lO9baXNKDytQznjRlZaDjBqZIXloWlcX6F1p/Da7n4O4Rd7BhBQHXUS7YqUz+QhWXMS5I29F8w8TQcmNyvLOZDfg7DBSOTNPZb+wMwRIaUkv/lKCBVyNAHi9Tdr0t3pkFviQNhFWQYyxCPCENJqw5lBQ="
  secret_access_key:
    secure: "QWIfZB81huUytlM9QvOCMtgYxM+Ho5qIOYKs3dqW3LGEZPFvTjd1gW0J2D5+8njsYnNEoHCVYACGicf54bevgvsz+ytspVFQVtVmTcLpCzFduodNW7hhYjKJL/sVDJ2gAeJT32A//CImQG32OMFbBJcYwIk/IlsHfkbiZdSVGpFkLE68rWqdi4LFIHbjaWkvhXF0M2sn1S/HLQh6P3u2bFPckINFNejOlSujfu1KYI+4qSmFUZOb3B8R+sf/P7DBumh75yK0wBdsRYZg/ugGOrmKr7qunYNdaoJIFzD4/MJwkjmkdBohO6C9h+Y8R1FWiG/ntnI7PdMg+WjhJRiJo9UJoBx3KC2MlEl+GtHYQZcraEkXOEuGf1JoUArAPGi8Jkb8+NCQu7k7nTQdCImadjiPNbd9Td6joHXbdAmRHHnlLJtF0UyOQj+Ex/lxlhWa/9vEhLvYpZuZBGJ1owebBqS6DqD7UxUKxJ92jG5vhx/ycPHdo+MTK11e5nTNL/CwZaajCv/7MXt8H1+UOzAKl1NhH2XXhBIEKmifaEj1BfCyzeNI5tljWY8du2QMMVJtFoFXN+dnKmjnFOgTT3062UsaulgGZv+yzzmigGjU9RitHo3fW8UcoW/MbA655bMxBPGFSnUDm1y+cmi/C5uLOoClPza49w4e8CvYV19nU+Q="
  bucket: cagataygurturk.com
  skip_cleanup: true
  region: eu-west-1
  local_dir: _site